### ISSUE TITLE
Swerve Drive Field-Oriented Control

### ISSUE THREAD

**Issue by alrazzi** [the-gearheads/SwerveTest#1]
The swerve chassis is almost completed (a bit of wiring and it'll be done). We need to develop code such that all the wheels are in sync, they rotate to the correct angle, and move at the correct speeds so that the robot produces the desired driving behavior. One of the key pros to swerve drive is field-oriented control, and so ultimately we need to ensure predictable, smooth motion with field-oriented control of the swerve test bot.

**Comment by alrazzi** [comment]
Currently in progress.

**Comment by person4268** [comment]
This should already work? I believe I'm already using ChassisSpeeds.fromFieldRelativeSpeeds()? You can swap driveFieldRelative() out for regular drive(), I believe. I'll go and make it an NT option, though. Reopen if it's still an issue, or there's more to discuss.

**Comment by alrazzi** [comment]
We'll try it out today and hopefully it works as planned

**Comment by alrazzi** [comment]
Swerve works mostly but there are some problems we'd like to fix before we can call it a day. The minor problems are narrowed down and specified in their separate issues.
