### ISSUE TITLE
Angleoffsets do not persist

### ISSUE THREAD

**Issue by alrazzi** [the-gearheads/SwerveTest#4]
When you power cycle the robot, the angle offsets set to the steer motors do not persist.

**Comment by person4268** [comment]
The problem is less that they don't persist on reboot, but more that they persist when the robot code restarts.
Workaround: ensure that the offsets get set only once per roborio boot
 Problem with said workaround: what if roborio reboots but motor controllers don't reset

**Comment by alrazzi** [comment]
This issue has been solved in PR #5

**Comment by person4268** [comment]
For the record, github has a feature where you can say stuff like "Fixed in #n"l or "Fixed by #n" and it'll pick up on that and link the issue and PR together (or you can do it manually)

**Comment by person4268** [comment]
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Comment by alrazzi** [comment]
oh neat!
